# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            WebCBT
tagline:          'Web based CBT Tool'
description:      'Web based Cognitive Behavioral Therapy tool'
url:              http://webcbt.github.io
baseurl:          http://webcbt.github.io/

author:
  name:           'Prashant Shah'
  url:            http://webcbt.github.io

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/webcbt/webcbt
